### PR TITLE
Index OCP 4 networking information

### PR DESCRIPTION
**Pull request by rsevilla87**
Depends on https://github.com/cloud-bulldozer/stockpile/pull/102
Network attachment definitions are indexed in a separate index as we may have many resources of this type.

### CODE REVIEW

**Comment by rsevilla87** [comment]
@aakarshg @jtaleric PTAL

**Comment by rsevilla87** [comment]
@aakarshg @dry923  I've moved the string replacement code to a library since it's also required to parse net-attach-definitions annotations.

**Comment by aakarshg** [comment]
> Depends on [cloud-bulldozer/stockpile#102](https://github.com/cloud-bulldozer/stockpile/pull/102)
> Network attachment definitions are indexed in a separate index as we may have many resources of this type.

The depends-on is not added to scribe yet.

**Comment by rsevilla87** [comment]
> > Depends on [cloud-bulldozer/stockpile#102](https://github.com/cloud-bulldozer/stockpile/pull/102)
> > Network attachment definitions are indexed in a separate index as we may have many resources of this type.
> 
> The depends-on is not added to scribe yet.

I know, this was just for reference :)

**Review by jtaleric — APPROVED** [review]
LGTM!

**Review by dry923 — APPROVED** [review]
LGTM

**Pull request merged**
