### PR TITLE
Add sysctl and meminfo modules

### PR DESCRIPTION
**Pull request by rsevilla87**
Depends on https://github.com/cloud-bulldozer/stockpile/pull/95

### CODE REVIEW

**Comment by aakarshg** [comment]
ok to test

**Comment by aakarshg** [comment]
@rsevilla87 do you've example documents in ES for this ?

**Comment by rsevilla87** [comment]
@aakarshg, emitting one document per sysctl entry would require to perform several modifications in the scribe framework. Are we willing to do this?

**Comment by aakarshg** [comment]
> @aakarshg, emitting one document per sysctl entry would require to perform several modifications in the scribe framework. Are we willing to do this?

@rsevilla87 there's two ways to go at this... either we can make changes to scribe to handle modules emitting a list of documents, or we can feed a list to scribe which scribe already supoorts https://github.com/cloud-bulldozer/scribe/blob/master/transcribe/render.py#L20 so essentially we'll need to update stockpile to emit a list of sysctl entries. kind of similar to how we do it for cpuvulnerabilities if my memory serves right.

**Comment by rsevilla87** [comment]
@aakarshg I've modified sysctl code to stop parsing sysctl entries, since ES fails to index them when more than 1k different entries are found (this happens in my laptop so a larger system would probably have more entries) due to the field limits of the index.
With this change sysctl entries will be indexed as raw data.

**Comment by aakarshg** [comment]
hi @rsevilla87 do you've any example documents from either?

**Review by aakarshg — APPROVED** [review]
nice work @rsevilla87

**Pull request merged**
